### ISSUE TITLE
SAS indentation with PROC SQL not quite perfect

### ISSUE THREAD

**Issue by wsprague** [akanosora/vimfiles#2]
First -- thanks so much for maintaining the SAS syntax file!  I love it, except for one thing -- proc sql doesn't work quite perfect on the "quit" keyword.

Here is a test case.  Note that the "quit" keyword doesn't get reindented back like the "run" keyword.

I am using version 3.0 of the sas syntax file, distributed with the latest stable of vim, 8.1.

Thanks!

```
proc sql;
    select 1 from boo;
    quit;

data ack;
    set bardl;
run;
```

**Comment by akanosora** [comment]
You can save the latest copy under .vim/indent under your user folder if you are using Linux/UNIX/Mac, or vimfiles\indent if you are using Windows.
